# Shopify app configuration
# https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "913c5aca61e254c4ffbb9c0b8dea2a65"
name = "personalize-preview"
application_url = "https://personalize-preview-shopify.tfwandre.workers.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[access_scopes]
scopes = "read_files,write_app_proxy,write_files,write_products"
optional_scopes = ["read_orders", "read_publications", "write_publications"]

[auth]
redirect_urls = ["https://personalize-preview-shopify.tfwandre.workers.dev/auth/callback"]

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request"]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/redact"]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = ["shop/redact"]
  uri = "/webhooks/shop/redact"

[app_proxy]
url = "/app-proxy"
prefix = "apps"
subpath = "personalize-preview"
