# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "913c5aca61e254c4ffbb9c0b8dea2a65"
application_url = "https://example.com"
embedded = true
name = "personalize-preview"

[webhooks]
api_version = "2026-10"

[access_scopes]
scopes = "write_products,write_metaobjects,write_metaobject_definitions,write_app_proxy,read_files,write_files"

[auth]
redirect_urls = ["https://example.com/api/auth"]

[app_proxy]
url = "/app-proxy"
prefix = "apps"
subpath = "personalize-preview"

[build]
automatically_update_urls_on_dev = true