query CartTransformRunInput {
  presentmentCurrencyRate
  cart {
    lines {
      id
      cost {
        amountPerQuantity {
          amount
        }
      }
      personalized: attribute(key: "_Personalized") { value }
      designConfirmed: attribute(key: "_Design confirmed") { value }
      personalizedSides: attribute(key: "_Personalized sides") { value }

      frontArtworkPreview: attribute(key: "_Front artwork preview") { value }
      frontArtworkFile: attribute(key: "_Front artwork file") { value }
      frontApprovedProof: attribute(key: "_Front approved proof") { value }
      frontPrintQuality: attribute(key: "_Front print quality") { value }
      frontPrintSize: attribute(key: "_Front print size") { value }
      frontArtworkPlacement: attribute(key: "_Front artwork placement") { value }
      frontText: attribute(key: "Front text") { value }

      backArtworkPreview: attribute(key: "_Back artwork preview") { value }
      backArtworkFile: attribute(key: "_Back artwork file") { value }
      backApprovedProof: attribute(key: "_Back approved proof") { value }
      backPrintQuality: attribute(key: "_Back print quality") { value }
      backPrintSize: attribute(key: "_Back print size") { value }
      backArtworkPlacement: attribute(key: "_Back artwork placement") { value }
      backText: attribute(key: "Back text") { value }

      merchandise {
        __typename
        ... on ProductVariant {
          id
          product {
            title
            backSurcharge: metafield(namespace: "custom", key: "personalize_back_surcharge") {
              value
            }
            backFeeVariantId: metafield(namespace: "custom", key: "personalize_back_fee_variant_id") {
              value
            }
          }
        }
      }
    }
  }
}
